[DEFAULT]
AccessType = OnPremise
SignOfLifeLog = 1
#Default = 43. Count up for every additional loadpoint
Deviceinstance = 43
#Read readme.md first! Default = 0. Count up for every additional loadpoint
LoadpointInstance = 0
# Charger AC-Position: 0 = AC out, 1 = AC in
AcPosition = 1
# are chargeVoltages given in http://[evcc-ip]:7070/api/state under "loadpoints"? 1 = yes, 0 = no
setVoltages = 0
# are chargeCurrents given in http://[evcc-ip]:7070/api/state under "loadpoints"? 1 = yes, 0 = no
setCurrents = 0

[ONPREMISE]
Host=192.168.1.2:7070
